version: '3.9'

services:
  web:
    build: .
    command: gunicorn mytodolist.wsgi:application --bind 0.0.0.0:8000 --workers 3
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      SECRET_KEY: ${SECRET_KEY:-$(python -c "from secrets import token_urlsafe; print(token_urlsafe(50))")}
  
