# Generated by Django 5.2.4 on 2025-07-31 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=800)),
                ('text', models.TextField(blank=True, max_length=1800, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('is_done', models.BooleanField(default=False)),
            ],
        ),
    ]
