# Generated by Django 5.2.4 on 2025-07-31 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmgr', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='is_done',
            new_name='done',
        ),
    ]
